#ifndef ENV_STYLE_H
#define ENV_STYLE_H

// Style

#define EDITOR_BG 0xF2F2F2
#define EDITOR_MIN_SIZE 800, 600
#define EDITOR_DEF_SIZE 1200, 720

#define EDITOR_EDITA_BG 0xBED8D4

#define EDITOR_HEAD_MIDDLE_SPACING 8
#define EDITOR_HEAD_MARGIN 5
#define EDITOR_HEAD_SEPARATOR ":/asset/img/leftArrow.svg"
#define EDITOR_HEAD_SEPARATOR_HEIGHT 12

#define EDITOR_PROPTAB_WIDTH 300
#define EDITOR_PROPTAB_BG 0xFFFFFF
#define EDITOR_PROP_HELP_MIN_HEIGHT 200
#define EDITOR_PROP_SPACING 20
#define EDITOR_PROP_FORM_WIDTH 260
#define EDITOR_TIME_REFRESH_RESIZE 5 // ms

#define LOADING_ICON_SIZE 80 // Page viewer

#define EDITOR_PAGE_SHADOW_RADIUS 80
#define EDITOR_PAGE_SHADOW_COLOR QColor(170, 170, 170)

#endif // ENV_STYLE_H
